I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/a1s1.rpy", line 187, in script
    "Он почти итальянский с интонациями и перекатывающимися буквами "Р", но в то же время определенно не итальянский.."
  File "renpy/common/00library.rpy", line 268, in say
    who(what, interact=interact, *args, **kwargs)
Exception: Say has image attributes (u'\u0420',), but there's no image tag associated with the speaking character.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/a1s1.rpy", line 187, in script
    "Он почти итальянский с интонациями и перекатывающимися буквами "Р", но в то же время определенно не итальянский.."
  File "D:\renpy-7.3.5-sdk\renpy\ast.py", line 708, in execute
    renpy.exports.say(who, what, *args, **kwargs)
  File "D:\renpy-7.3.5-sdk\renpy\exports.py", line 1343, in say
    renpy.store.say(who, what, *args, **kwargs)
  File "renpy/common/00library.rpy", line 268, in say
    who(what, interact=interact, *args, **kwargs)
  File "D:\renpy-7.3.5-sdk\renpy\character.py", line 1073, in __call__
    old_attr_state = self.handle_say_attributes(False, interact)
  File "D:\renpy-7.3.5-sdk\renpy\character.py", line 942, in handle_say_attributes
    if self.resolve_say_attributes(predicting, attrs):
  File "D:\renpy-7.3.5-sdk\renpy\character.py", line 868, in resolve_say_attributes
    raise Exception("Say has image attributes %r, but there's no image tag associated with the speaking character." % (attrs,))
Exception: Say has image attributes (u'\u0420',), but there's no image tag associated with the speaking character.

Windows-8-6.2.9200
Ren'Py 7.3.5.606
Adastra 12
Tue Feb 04 03:12:45 2020
